import BookForm from '@/components/Form/BookForm';
import MainLayout from '@/components/Layout/MainLayout';
import Head from 'next/head';
import React, { ReactElement } from 'react';

const AddBook = () => {
  return (
    <>
      <Head>
        <title>Add Book | Spotbook</title>
        <meta name="spotlite" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-w-screen flex min-h-screen items-center justify-center">
        <div className="flex flex-col gap-1 px-5 lg:flex-row lg:gap-32">
          <BookForm />
        </div>
      </main>
    </>
  );
};

export default AddBook;

AddBook.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};
