import SignupForm from '@/components/Form/SignupForm';
import { ModeToggle } from '@/components/ui/mode-toggle';
import { ThemeProvider } from '@/components/ui/theme-provider';
import Head from 'next/head';
import { Toaster } from 'sonner';
import React from 'react';

const Signup = () => {
  return (
    <>
      <Head>
        <title>Signup | SpotBook</title>
        <meta name="spotlite" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider attribute="class" defaultTheme="system">
        <main className="min-w-screen flex min-h-screen items-center justify-center">
          <div className="flex flex-col gap-1 px-5 lg:flex-row lg:gap-32">
            <SignupForm />
          </div>
          <div className="fixed bottom-5 right-5 z-[50] rounded-lg bg-background">
            <ModeToggle />
          </div>
          <Toaster richColors closeButton />
        </main>
      </ThemeProvider>
    </>
  );
};

export default Signup;
