import HeaderLined from '@/components/HeaderLined';
import Head from 'next/head';
import React from 'react';
import { Toaster } from 'sonner';

const Signup = () => {
  return (
    <>
      <Head>
        <title>Admin Registration | Kazee Employee Management</title>
        <meta name="Kazee" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-w-screen min-h-screen gap-3 px-3 pb-10 pt-16 md:px-28 md:pt-24 2xl:px-72 ">
        <HeaderLined className="text-primary absolute left-0">
          Signup
        </HeaderLined>
        <Toaster richColors closeButton />
        {/* <AdminRegistrationForm /> */}
      </main>
    </>
  );
};

export default Signup;
